stages:
  data_preparation:
    cmd: python src/data/prepare_data.py
    deps:
      - data/train.csv
      - src/data/prepare_data.py
    params:
      - selected_features
    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv

  hyperparameter_tuning:
    cmd: python src/models/tune_hyperparameters.py
    deps:
      - data/processed/X_train.csv
      - data/processed/y_train.csv
      - src/models/tune_hyperparameters.py
    params:
      - hyperparameter_tuning
    outs:
      - models/best_params.json

  train:
    cmd: python src/models/train_model.py
    deps:
      - data/processed/X_train.csv
      - data/processed/y_train.csv
      - models/best_params.json
      - src/models/train_model.py
    params:
      - xgboost.random_state
    outs:
      - models/xgb_model.pkl
      - models/preprocessor.pkl

  evaluate:
    cmd: python src/models/evaluate_model.py
    deps:
      - models/xgb_model.pkl
      - models/preprocessor.pkl
      - data/processed/X_test.csv
      - data/processed/y_test.csv
      - src/models/evaluate_model.py
    params:
      - metrics
    metrics:
      - models/metrics.json:
          cache: false
