stages:

  data_preparation:
    cmd: PYTHONPATH=. python src/data/prepare_data.py
    deps:
      - data/train.csv
      - src/data/prepare_data.py
    params:
      - selected_features
    outs:
      - data/train_data.joblib
      - data/val_data.joblib

  hyperparameter_tuning:
    cmd: PYTHONPATH=. python src/models/tune_hyperparameters.py
    deps:
      - data/train_data.joblib
      - src/models/pipeline.py
      - src/models/tune_hyperparameters.py
    params:
      - hyperparameter_tuning
    outs:
      - models/best_params.json

  train:
    cmd: PYTHONPATH=. python src/models/train_model.py
    deps:
      - models/best_params.json
      - src/models/pipeline.py
      - src/models/train_model.py
      - data/train_data.joblib
    outs:
      - models/pipeline.joblib

  evaluate:
    cmd: PYTHONPATH=. python src/models/evaluate_model.py
    deps:
      - models/pipeline.joblib
      - src/models/evaluate_model.py
      - data/val_data.joblib
    metrics:
      - models/metrics.json:
          cache: false