stages:

  data_preparation:
    cmd: python src/data/prepare_data.py
    deps:
      - data/train.csv
      - data/test.csv
      - src/data/prepare_data.py
    params:
      - selected_features
    outs:
      - data/processed_data.joblib

  hyperparameter_tuning:
    cmd: python src/models/tune_hyperparameters.py
    deps:
      - data/processed_data.joblib
      - src/models/tune_hyperparameters.py
    params:
      - hyperparameter_tuning
    outs:
      - models/best_params.json

  train:
    cmd: python src/models/train_model.py
    deps:
      - data/processed_data.joblib
      - models/best_params.json
      - src/models/train_model.py
    params:
      - xgboost.random_state
    outs:
      - models/pipeline.joblib

  evaluate:
    cmd: python src/models/evaluate_model.py
    deps:
      - models/pipeline.joblib
      - data/processed_data.joblib
      - src/models/evaluate_model.py
    params:
      - metrics
    metrics:
      - models/metrics.json:
          cache: false