selected_features:
- RoofMatl
- Condition2
- KitchenQual
- BsmtQual
- GrLivArea
- OverallQual
- BsmtExposure
- BldgType
- SaleType
hyperparameter_tuning:
  n_trials: 15
  n_estimators:
    low: 50
    high: 1000
  max_depth:
    low: 3
    high: 15
  learning_rate:
    low: 0.001
    high: 0.3
